language: python
python:
  - "2.7"
addons:
  postgresql: "9.1"
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp project/settings/local.py-travis project/settings/local.py
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r requirements/dev.txt
# command to run tests, e.g. python setup.py test
script: python manage.py test
